# Generated by Django 5.2.4 on 2025-07-26 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="car_options",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mini", "Mini"),
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("7seater", "7 Seater"),
                        ],
                        max_length=10,
                    ),
                ),
                ("availability", models.BooleanField()),
                ("image", models.ImageField(upload_to="cab/")),
            ],
        ),
    ]
