# Generated by Django 5.2.4 on 2025-07-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car_options",
            name="image",
            field=models.ImageField(upload_to="cabs/"),
        ),
    ]
