# Generated by Django 5.2.4 on 2025-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cab", "0002_alter_car_options_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_options",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
