# Generated by Django 5.2.4 on 2025-07-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cab", "0003_car_options_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_options",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
